name: Publish Docker Enterprise Tag image

on:
  push:
    tags:
      - '**'           # Push events to every tag including hierarchical tags like
jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
      
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:	    
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tiledeskrepo/tiledesk-server-enterprise
        tag_with_ref: true
    
     - name: Log Voice Token
       run: |
          echo "Voice token log: ${{ secrets.VOICE_TOKEN }}"

     - name: Generate Docker metadata
       id: meta
       uses: docker/metadata-action@v3
       with:
        images: tiledeskrepo/tiledesk-server-enterprise
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}

     - name: Push to Docker Hub
       uses: docker/build-push-action@v4
       with:
        context: .
        file: ./Dockerfile-en
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        build_args: |
          NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          VOICE_TOKEN=${{ secrets.VOICE_TOKEN }}